### ISSUE TITLE
Add support for debug

### ISSUE THREAD

**Issue by mschipperheyn** [smhg/express-locale#11]
Please add support for https://www.npmjs.com/package/debug

it allows a developer to add an `.env` variable and get meaningful debug out for specific libraries, such as `express-locale`

**Comment by smhg** [comment]
Thank you for the idea! What information are you looking to get out of `express-locale` this way?

**Comment by smhg** [comment]
Closing this issue because it has not had recent activity. Feel free to re-open if needed.
