### ISSUE TITLE
Add option to limit accepted locales 

### ISSUE THREAD

**Issue by johnlife** [smhg/express-locale#12]
I'd really like to have an option to limit accepted locales to a predefined set.
Something like:

    app.use(localeMiddleware({
        priority: ["session", "accept-language", "default"],
        "accept-language": ["en_US", "kh_KH"],
        "default": "en_US",
        lookups: {
            session: (req) => req.session.locale ? languages.map(req.session.locale) : undefined
        },
    }));

Note set of allowed locales for 'accept-language' source. So if user visits with 'accept-language: kh_KH' we got kh_KH locale, but if he visits with ru_RU or any other not listed in allowed set - this lookup produces null or undefined and falls back to next (default) lookup.

**Comment by smhg** [comment]
You can accomplish your example by using the `allowed` option, which is a whitelist for all lookups:
```javascript
app.use(localeMiddleware({
    priority: ["session", "accept-language", "default"],
    "default": "en_US",
    allowed: ["en_US", "kh_KH"],
    lookups: {
        session: (req) => req.session.locale ? languages.map(req.session.locale) : undefined
    },
}));
```
I'm not sure if whitelisting _per source_ makes much sense? Do you want to allow different locales when they are retrieved from the session lookup?

**Comment by smhg** [comment]
I'll close this for now, but please feel free to provide more information.
