### ISSUE TITLE
Date.toLocaleString (native) - RangeError: Invalid language tag: en_US

### ISSUE THREAD

**Issue by benpptung** [smhg/express-locale#18]
I just realized `Date.toLocaleString` expect en-US instead of en_US, and I know the following from the [this](http://codel10n.com/what-is-correct-locale-tag-en_us-vs-en-us/)

> when you’re configuring Unix environment, you have to define POSIX locale with underscore as en_US.UTF-8. On the other hand, if you’re trying to set locale (called CultureInfo) in your C# app it will be en-US...IETF locale tags are used in other modern standards such as those related to HTML, World Wide Web Consortium

I'm wondering if we should put a note in README to highlight that we need to convert en_US to en-US? Also, add another method to get the locale string? 

Because, if we use req.locale.toString() and put the locale into Date.toLocaleString(), it will throw RangeError: Invalid language tag.

**Comment by smhg** [comment]
I'm actually in favor of changing the format to hyphen notation (because of Intl compatibility). Would you want to send a PR?

**Comment by benpptung** [comment]
I'm wondering because it looks like a breaking change if someone is using underscore format.
PR made, but I'm sorry I am still in Node.js 4 env, so I cannot run/edit `npm test`. Hope it helps and if any edit is necessary, please feel free to let me know :)

https://github.com/smhg/express-locale/pull/19

**Comment by smhg** [comment]
Yes, it is definitely a breaking change and it will be a new major release. But it is ok if it improves things.
