### ISSUE TITLE
1.0.0 roadmap

### ISSUE THREAD

**Issue by smhg** [smhg/express-locale#6]
- ~~Split up lookups into separate files~~
- ~~Lookup functions should be thunks that take middleware options~~
- ~~Make adding custom lookups more intuitive (instead of config + method call on instance)~~
- ~~Add a querytstring lookup~~
- ~~Add more real-world (lookup combinations) tests~~
- ~~Add changelog~~

Future versions:
- Test individual components
- Add a path lookup
- Add an IP geocoding lookup (see #5)

**Comment by smhg** [comment]
@stutrek would you like to contribute to the above? And/or suggest other ideas?

**Comment by stutrek** [comment]
I like the path lookup idea. Also, having a query string set a cookie could be very handy for QA.

It's also possible that someone used the extension API and has a useful function already. Is there a way to search for projects in github that depend on this?
